---
- name: "Add Google key"
  apt_key:
        url=https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: "Add Google repository"
  apt_repository:
        filename=google.list
        repo='deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'

- name: "Add node key"
  apt_key:
        url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: "Add node repository"
  apt_repository:
        filename=nodesource.list
        repo='deb https://deb.nodesource.com/node_{{ node_version }} {{ ansible_distribution_release }} main'
